<a href="https://colab.research.google.com/github/ibrahimjamil/ML_MATHS/blob/main/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def square(x):
  return x ** 2

try:
  square("a")
except TypeError as e:
  print("TypeError: ", e)

TypeError:  unsupported operand type(s) for ** or pow(): 'str' and 'int'


In [ ]:
def square(x: int) -> int:
  return x ** 2

try:
  square("2")
except TypeError as e:
  print("TypeError: ", e)

TypeError:  unsupported operand type(s) for ** or pow(): 'str' and 'int'


In [ ]:
import numpy as np

matrix = np.array([[1, 2], [3, 4], [5, 6]])  # 3 x 2 matrix
vector = np.array([7, 8])  # length 2 vector
tensor = np.array([
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]]
])

print(matrix @ vector)  # length 3 vector
print(tensor.shape)
try:
  vector = np.array([7, 8, 9])  # length 3 vector
  print(matrix @ vector)
except ValueError as e:
  print("ValueError:", e)

[23 53 83]
(2, 3, 2)
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [ ]:
import numpy as np
set_second_to_zero = np.array([[1, 0],
                               [0, 0]])
vector = [10, 1]
print((set_second_to_zero @ vector))
assert (set_second_to_zero @ vector)[1] == 0

W = np.array([[1, 2], [-1, 1]])
X = np.array([[1/10, 1/5], [1/4, 1]])
Y = np.array([[3, 1], [0.1, 0]])
Z = np.array([[1, 0], [0, 1]])

def their_pipeline(v):
    after_W = np.matmul(W, v)
    after_X = np.matmul(X, after_W)
    after_Y = Y @ after_X
    after_Z = Z @ after_Y
    return after_Z

V = [1,0]  # define V here

print(their_pipeline(V))

batch_of_vectors = np.array([[1, 3, 5, 7], [1, 3, 5, 7]])
print(batch_of_vectors)

print(batch_of_vectors.T.shape)

for vector in batch_of_vectors.T:  # by default, numpy iterates over rows, but we want cols
  print(vector)

matrix = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
rows = [row for row in matrix]  # split the matrix into 4 rows with shape (2, 1)

vector = [3, 5]
print(rows, matrix @ vector, [row @ vector for row in rows])
np.allclose(matrix @ vector,
np.hstack([row @ vector for row in rows]))
print(np.hstack([row @ vector for row in rows]), [row @ vector for row in rows])

[10  0]
[-1.05 -0.01]
[[1 3 5 7]
 [1 3 5 7]]
(4, 2)
[1 1]
[3 3]
[5 5]
[7 7]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])] [13 29 45 61] [np.int64(13), np.int64(29), np.int64(45), np.int64(61)]
[13 29 45 61] [np.int64(13), np.int64(29), np.int64(45), np.int64(61)]


In [ ]:
import numpy as np
matrix = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
splits = matrix[:2], matrix[2:]  # split matrix into two matrices of shape (2, 2)
print(matrix)
print(splits)

vector = [3, 5]
print(matrix @ vector, [split @ vector for split in splits])

np.allclose(matrix @ vector,
            np.hstack([split @ vector for split in splits]))

arrays = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8]])]
print(arrays)

print(np.concatenate(arrays))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]))
[13 29 45 61] [array([13, 29]), array([45, 61])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
